version: 2.0.1.{build}
branches:
  only:
  - master
  - dev
  - ci
configuration: Release
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
services:
  - mongodb
clone_folder: c:\projects\cars
clone_depth: 1
environment:
  MONGODB_HOST: localhost
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:
    secure: 1/s9jKeXYZlGBAVrpRFbAgSFCP2WhW/EwYoCJRqDNx0Kwn0KknzyMCHeGumafG1N
skip_commits:
  message: /updated readme.*/
build_script:
- ps: .\build.ps1 -Target AppVeyor
test: off
artifacts:
  - path: artifacts\test-results\*.*
    name: test-results
  - path: artifacts\nugets\*.*
    name: nugets
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: xI3sXl+1c3YUwXa2UXa2PEIaP/VFd9w85s2zno5lG36Un0rxbnQg+wyZjKyu8rNr
  on:
    branch: master
- provider: NuGet
  skip_symbols: true
  server: https://www.myget.org/F/cars/api/v2/package
  api_key:
    secure:  xI3sXl+1c3YUwXa2UXa2PEIaP/VFd9w85s2zno5lG36Un0rxbnQg+wyZjKyu8rNr
  on:
    branch: 
    - dev
    - ci